DEBUG: True
seed: ~

# experiment settings
EXP_NAME: 'Auto lens design'

# # lens target example 1 (camera lens)
# foclen: 85.0
# fov: 40.0
# fnum: 4.0
# bfl: 18.0
# thickness: 120.0
# surf_list: [["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric", "Spheric"], ["Aperture"], ["Spheric", "Spheric", "Spheric"], ["Spheric", "Aspheric"], ["Spheric", "Aspheric"]]
# lrs: [1e-3, 1e-4, 1e-2, 1e-4]

# lens target example 2 (mobile lens)
foclen: 6.1
fov: 85.0
fnum: 1.9
bfl: 0.97
thickness: 7.3
surf_list: [["Aperture"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"]]
lrs: [1e-3, 1e-3, 1e-2, 1e-3]

# # lens target example 3 (camera lens)
# foclen: 35.0
# fov: 50.0
# fnum: 2.0
# bfl: 18.0
# thickness: 120.0
# surf_list: [["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Aperture"], ["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric"], ["Spheric", "Spheric"]]
# # lrs: [1e-3, 1e-3, 0.0, 0.0]
# lrs: [1e-4, 1e-4, 0.0, 0.0]
#
# # lens target example 4 (mobile lens)
# foclen: 5.0
# fov: 90.0
# fnum: 2.0
# bfl: 1.5
# thickness: 10.0
# surf_list: [["Aperture"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"]]
# lrs: [1e-3, 1e-3, 1e-2, 1e-3]

# # lens target example 5 (camera lens)
# foclen: 30.0
# fov: 70.0
# fnum: 2.8
# bfl: 18.0
# thickness: 50.0
# surf_list: [["Aspheric", "Aspheric"], ["Aperture"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"], ["Aspheric", "Aspheric"]]
# lrs: [1e-3, 1e-3, 1e-2, 1e-4]